### ISSUE TITLE
Use the keyboard UI for input

### ISSUE THREAD

**Issue by cassidyjames** [avojak/warble#1]
**Is your feature request related to a problem? Please describe.**

When I saw the cute little keyboard buttons, I wanted to click them! :D

**Describe the solution you'd like**

I think it'd make sense for them to be buttons. This would also make the game more accessible e.g. with just the mouse and on touch devices.

**Describe alternatives you've considered**

You could _not_ make them clickable, I guess :joy: 

**Additional context**

If you make the game playable with just the mouse/touch, you'd probably need to add a submit and backspace button to the UI, too.

**Comment by avojak** [comment]
Yes! This was something I considered initially but it didn't make the MVP cut 🤣

I'll look into making some slight "pressed" variants of the keys too, that should look really nice.
