### ISSUE TITLE
Potential answers and accepted word list mismatch?

### ISSUE THREAD

**Issue by pemberj** [avojak/warble#11]
First, thanks for releasing this game, I've been enjoying it a lot!

**Describe the bug**
I had a round recently where the correct answer was not being accepted as a real word:

![Screenshot from 2022-01-12 21-40-18](https://user-images.githubusercontent.com/316075/149130340-b718d5e9-c804-4cbd-8a34-a984ef4aafa8.png)

I guess this is filtered out as a potentially problematic word, but was still able to come up as the answer.

**Expected behavior**
The allowed word list and possible answers list should be exactly the same, with no words appearing in one but not the other.

**Environment (please complete the following information):**
 - OS Version: Elementary OS 6.1
 - Warble Version 1.0.1

**Comment by avojak** [comment]
That's definitely a bug, thanks for reporting! There's must've been something wrong with how I validated the possible answers as a strict subset of the dictionary.

**Comment by avojak** [comment]
Resolved with 2dff0671141fe69fa0d6772455dd8589c520d64d
