### ISSUE TITLE
Force the use of the elementary stylesheet on other platforms.

### ISSUE THREAD

**Issue by AbrarSL** [avojak/warble#15]
**Describe the bug**
Running the AppCenter flatpak on a system that uses a different GTK stylesheet (Adwaita) causes the app to look odd.

**To Reproduce**
Simply install the application on a non-elementary system.

**Expected behavior**
App should maintain it's elementary style and branding regardless of the platform it is run on.

**Screenshots**
![Screenshot from 2022-01-18 12-01-21](https://user-images.githubusercontent.com/69783006/149883338-31d1aa14-15b0-4ac6-b17a-d6550cc29fef.png)
![Screenshot from 2022-01-18 12-01-42](https://user-images.githubusercontent.com/69783006/149883357-ef0a2ca4-f9ec-4e58-b0df-8eeaadaa41fb.png)

**Environment (please complete the following information):**
 - OS Version:
```
Linux abrar-desktop 5.16.0-zen1-1-zen #1 ZEN SMP PREEMPT Mon, 10 Jan 2022 20:12:01 +0000 x86_64 GNU/Linux
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

 - Warble Version
V1.1.1

**Comment by AbrarSL** [comment]
https://github.com/elementary/granite/pull/486

^Could be used to solve the issue.

**Comment by avojak** [comment]
I was just thinking about how I would go about doing this yesterday - thanks for pointing me to the Granite util!

**Comment by avojak** [comment]
Actually looks like that util was pulled back out of Granite: https://github.com/elementary/granite/pull/501

Reaching out to the elementary devs about what the current recommendation is. Using the same code that Granite had used works, but I'd like to avoid that if possible.

**Comment by tronta** [comment]
Thanks for the great game. My question is, why would one want to enforce the Elementry style on other DEs?
For me it looks like this:
![grafik](https://user-images.githubusercontent.com/5135577/152097620-b7ab8a08-1ac7-4d61-8a14-02a0e7c23c58.png)

**Comment by avojak** [comment]
The app is developed for elementary OS first and foremost. Supporting other platforms directly isn't something that I'm currently interested in doing, so by forcing the elementary OS stylesheet I can ensure that things will look exactly as intended. It's a happy medium, in my opinion, to make it a good experience for the users on other platforms while still minimizing the maintenance effort on my end.
