### ISSUE TITLE
Changing the contrast mode or difficulty level does nothing

### ISSUE THREAD

**Issue by rwmpelstilzchen** [avojak/warble#22]
`uname` output:

    Linux bluebox 5.15.11-arch2-1 #1 SMP PREEMPT Wed, 22 Dec 2021 09:23:54 +0000 x86_64 GNU/Linux

`pacman -Qi warble | grep ^Version` output:

    Version         : 1.2.0-2

**Comment by avojak** [comment]
When you're changing those settings, have any guesses been made?

Changing the difficulty before a guess has been submitted doesn't change anything visually (unless you got to hard mode which uses 6-letter words). Similarly the high contrast mode applies to the yellow/green contrast for tiles after a guess is submitted.
