### ISSUE TITLE
Closing One Warble Window Closes All Open Instances

### ISSUE THREAD

**Issue by chrisdotcode** [avojak/warble#24]
**Describe the bug**
Closing one Warble window closes all open instances.

**To Reproduce**
1. Open many Warble windows.
2. Close one of them.
3. They all fall down.

**Expected behavior**
Closing one window should only close that one window.

**Environment (please complete the following information):**
 - OS Version: elementary OS 6.1
 - Warble Version: 1.2.0

**Additional context**
I wonder also, how Warble instances are tracking separate internal state, and if you play multiple games across different window instances, if the gameplay statistics per window will either clobber each other, or aggregate.

**Comment by avojak** [comment]
Currently there's nothing to deconflict internal state across multiple windows. I'm leaning towards simply restricting to a single window instance rather than trying to deconflict multiple. Having multiple games going at the same time doesn't really seem like a normal use case to me.

**Comment by chrisdotcode** [comment]
While I'm sure it's uncommon to open multiple instances, I don't really see the utility of not-allowing it as per the [zero, one, infinity rule](https://en.wikipedia.org/wiki/Zero_one_infinity_rule); I don't think the singleton case warrants "special" treatment in this case, either.

I suppose perhaps an issue could be if the code isn't set up internally to support it (although aside from statistics clobbering, from my limited testing, I was able to play two *different* games at once), but I think from a philosophical case, infinity instances should be supported (like infinity terminals, or infinity web browsers).
