### ISSUE TITLE
Users should be able to Reset their Gameplay Statistics

### ISSUE THREAD

**Issue by chrisdotcode** [avojak/warble#25]
**Is your feature request related to a problem? Please describe.**
Users should be able to reset their gameplay statistics.

**Describe the solution you'd like**
Upon viewing gameplay statistics, there could/should be a danger-level button on the other side of "close" that resets the gameplay stats.

**Describe alternatives you've considered**
The user can live forever in unending, agonizing toil of their imperfect scores being unresettable, and seethe in their imperfections indefinitely.

**Comment by avojak** [comment]
Thanks for the suggestion! I started implementing this for the initial release but wasn't happy with how the UI was looking for it and decided to not implement. Definitely a good feature to add! And the alternative is certainly not a happy one 🤣

**Comment by chrisdotcode** [comment]
How about a button opposite "close" on the stats page, per my suggestion?

**Comment by avojak** [comment]
IIRC the method to pack action buttons on the opposite side of the action area is deprecated, but I could be wrong. I also wasn't a big fan of using a button for that, and was instead looking at using a link with the destructive action style class.

**Comment by yalin** [comment]
I came here to write about this but I guess I am not the only one who wants reset statistics :)
eagerly waiting for it...
