### ISSUE TITLE
Does not work in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by PJW1820** [avojak/warble#26]
**Describe the bug**
1) Can open using applications
2) lower part of window is off the bottom of the screen
3) cannot move window
4) cannot close applications

**Environment (please complete the following information):**
 - OS Version: Ubuntu 20.04.3 LTS
 - Warble Version: unknown; latest install version via Flatpak

**Comment by avojak** [comment]
To clarify - the primary issue here is that the game window exceeds your screen size, so you are unable to move the window or close it?

As a temporary workaround, the application can be closed with the Ctrl+q keyboard shortcut.

**Comment by PJW1820** [comment]
Hi Andrew
I cannot move or close window.
Peter

**Comment by PJW1820** [comment]
Just tried again. AND I can move AND close the window.  Wil try game.
Peter

**Comment by PJW1820** [comment]
Is working now.  Probably had to restart laptop to get app properly
installed & set up.
Peter

**Comment by avojak** [comment]
Thanks for the update!
