### ISSUE TITLE
error: The type name `Granite.Dialog' could not be found

### ISSUE THREAD

**Issue by justineuro** [avojak/warble#27]
**Describe the bug**
Build failed.

**To Reproduce**
1. `git clone https://github.com/avojak/warble.git`
2. `meson build --prefix=$HOME/.local/usr`
3. `ninja -C build install`
4. See build fail message (please see attached file: [000ERR.txt](https://github.com/avojak/warble/files/8088037/000ERR.txt))

**Expected behavior**
Successful build.

**Environment (please complete the following information):**
 - OS Version: Debian GNU/Linux 10 
 - Warble Version: 1.2.0

**Comment by ChildishGiant** [comment]
Sounds like you need to install granite  https://github.com/elementary/granite

**Comment by justineuro** [comment]
Thanks for looking into this!
