### ISSUE TITLE
Claims word isn't word when it is

### ISSUE THREAD

**Issue by linprof** [avojak/warble#32]
**Describe the bug**
I entered the word of the male organ and the program claims it isn't a word when it certainly is.

**To Reproduce**
Enter the name of the male organ.
Notice you can't.

**Expected behavior**
For the word to be recognized.

**Screenshots**
![image](https://user-images.githubusercontent.com/102863639/161385303-446f1b26-a6ce-4fea-a3d3-dd0b484e9dfa.png)

**Environment (please complete the following information):**
 - OS Version: Fedora 36 KDE
 - Warble Version: 1.3.1

**Comment by ChildishGiant** [comment]
Words are taken from [sindresorhus/word-list](https://github.com/sindresorhus/word-list) which purposefully filters out "many common bad words"

**Comment by avojak** [comment]
Yep, exactly what @ChildishGiant said.

**Comment by linprof** [comment]
That's not a bad word...?
