### ISSUE TITLE
Getting Build Error:

### ISSUE THREAD

**Issue by ghost** [avojak/warble#33]
cc -Isrc/com.github.avojak.warble.p -Isrc -I../src -Idata -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/gee-0.8 -I/usr/include/granite -I/usr/include/libhandy-1 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -w -g '-DGETTEXT_PACKAGE="com.github.avojak.warble"' -pthread -MD -MQ src/com.github.avojak.warble.p/meson-generated_Widgets_GameArea.c.o -MF src/com.github.avojak.warble.p/meson-generated_Widgets_GameArea.c.o.d -o src/com.github.avojak.warble.p/meson-generated_Widgets_GameArea.c.o -c src/com.github.avojak.warble.p/Widgets/GameArea.c
../src/Widgets/GameArea.vala: In function ‘warble_widgets_game_area_update_states’:
../src/Widgets/GameArea.vala:383:12: error: incompatible types when assigning to type ‘WarbleModelsState’ {aka ‘enum <anonymous>’} from type ‘gconstpointer’ {aka ‘const void *’}
             rows.get(current_row).get(entry.key).state = entry.value;
            ^
../src/Widgets/GameArea.vala:402:12: error: incompatible types when assigning to type ‘WarbleModelsState’ {aka ‘enum <anonymous>’} from type ‘gconstpointer’ {aka ‘const void *’}
             var new_state = entry.value;
            ^
ninja: build stopped: subcommand failed.

**Comment by avojak** [comment]
Please provide the missing information from the GiHub issue template.

**Comment by bebing2** [comment]
It's still an issue, I just cannot spend any more time on it.

**Comment by ghost** [comment]
I believe updating my version of cmake resolved this issue.
