### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by upriver4** [avojak/warble#45]
**Is your feature request related to a problem? Please describe.**
Distros like Linux Mint and Elementary OS have started hiding or otherwise discouraging the use of unverified flatpaks. More will likely follow as verified apps approach 50% of Flathub

**Describe the solution you'd like**
Could you verify the flatpak on Flathub so people on these distros can find it?

**Describe alternatives you've considered**

**Additional context**
Here is a link to Flathub's verification documentation for app authors https://docs.flathub.org/docs/for-app-authors/verification/

**Comment by avojak** [comment]
<img width="338" alt="image" src="https://github.com/user-attachments/assets/b29ee748-6698-441e-80c6-cceea4402817">
Verified
